{
 "title": "Determined API Server Montoring",
 "description": "Monitors Determined API server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_job", "query": "det-master-api-server" }
  ]
 },
 "panels": [
  {
   "title": "p95 API response times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\"}[5m])) by (grpc_method,le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% requests exceeding 5s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|AllGather\",le=\"5\"}[5m])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|AllGather\",le=\"+Inf\"}[5m])) by (grpc_method)\n) * 100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handling_seconds_sum{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|Login|AllGather\"}[5m]))\n/\nsum by(grpc_method) (rate(grpc_server_handling_seconds_count{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|Login|AllGather\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rps by grcp_method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$prometheus_job\"}[1m])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors percent by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!~\"OK|NotFound|InvalidArgument\"}[1m])) by (grpc_method)\n / \nsum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!=\"OK|NotFound|InvalidArgument\"}[1m])) by (grpc_method)\n * 100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors per second by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!~\"OK|NotFound|InvalidArgument\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}