{
 "title": "Determined API Server Montoring",
 "description": "Monitors Determined API server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_job", "query": "det-master-api-server" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate Per Second by Sucess and Failure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_code=~\"^(OK|NotFound|InvalidArgument)$\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_code!~\"^(OK|NotFound|InvalidArgument)$\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{job=\"$prometheus_job\",grpc_type=\"unary\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Per Second by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$prometheus_job\",grpc_type=\"unary\"}[1m])) by (grpc_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "p95 API Response Times By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\"}[5m])) by (grpc_method,le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Requests Exceeding 5s By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|AllGather\",le=\"5\"}[5m])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_bucket{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|AllGather\",le=\"+Inf\"}[5m])) by (grpc_method)\n) * 100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handling_seconds_sum{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|Login|AllGather\"}[5m]))\n/\nsum by(grpc_method) (rate(grpc_server_handling_seconds_count{job=\"$prometheus_job\",grpc_type=\"unary\",grpc_method!~\"AllocationPreemptionSignal|Login|AllGather\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$prometheus_job\"}[1m])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Percent by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!~\"OK|NotFound|InvalidArgument\"}[1m])) by (grpc_method)\n / \nsum(rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!=\"OK|NotFound|InvalidArgument\"}[1m])) by (grpc_method)\n * 100.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Per Second by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handled_total{job=\"$prometheus_job\", grpc_type=\"unary\", grpc_code!~\"OK|NotFound|InvalidArgument\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}